{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime-ktx",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.7.0.aar",
          "url": "work-runtime-ktx-2.7.0.aar",
          "size": 23816,
          "sha512": "c1b4a68042f28506affebdaf872d852638410975732a689d6af279d35f1c3b4f6020b605e0ef710dfc65b9056af1741ce89331fc033e31d6b417c1faaac3579b",
          "sha256": "0069ca0ca3e0b34e40f0ab77c00edb85d20f3086823bcfc0d66dbd2eaae15e3f",
          "sha1": "e8e37b2d3577c08478cbcfa98691ee56171f3c1a",
          "md5": "2aae500e72e1b76a1484fa2514bb54a9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.7.0.aar",
          "url": "work-runtime-ktx-2.7.0.aar",
          "size": 23816,
          "sha512": "c1b4a68042f28506affebdaf872d852638410975732a689d6af279d35f1c3b4f6020b605e0ef710dfc65b9056af1741ce89331fc033e31d6b417c1faaac3579b",
          "sha256": "0069ca0ca3e0b34e40f0ab77c00edb85d20f3086823bcfc0d66dbd2eaae15e3f",
          "sha1": "e8e37b2d3577c08478cbcfa98691ee56171f3c1a",
          "md5": "2aae500e72e1b76a1484fa2514bb54a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-runtime-ktx-2.7.0-sources.jar",
          "url": "work-runtime-ktx-2.7.0-sources.jar",
          "size": 7782,
          "sha512": "b8963cf23164c72f59cce84d8d7d39805448cc7af6e02b1f8230ac0f6693baf98b87986fd3926a6db57627727991b04dd2a4637f6ac62f1e7c6a9bcaf047bdbd",
          "sha256": "d9655a6160ed571efd19245448e6bf6b373be2c9b796433d5fb4ded3913a9a5f",
          "sha1": "5c7b348ca80eaf8d6ce94228dd10a9d8715cf0e4",
          "md5": "ebad1971a708bba83785f65cf929f8bd"
        }
      ]
    }
  ]
}
