{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.2.1.aar",
          "url": "media3-exoplayer-1.2.1.aar",
          "size": 1334432,
          "sha512": "792011c28477fbc196e12af7ebbd999a844673739f864877559fcb57ca9867ceef5d6f478e8a23bfce00be561b160a48669a1645d202d2b895e8b5d420958e2a",
          "sha256": "85204c2fbcb4ea68fd11b9c45da16b691898147a21e3e9d95796ad5b45c41f30",
          "sha1": "5182aefe72fc90b77102a1010d23ec9e5b37909c",
          "md5": "90de4453ea60ac1a1162bc5db5698a4d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.2.1.aar",
          "url": "media3-exoplayer-1.2.1.aar",
          "size": 1334432,
          "sha512": "792011c28477fbc196e12af7ebbd999a844673739f864877559fcb57ca9867ceef5d6f478e8a23bfce00be561b160a48669a1645d202d2b895e8b5d420958e2a",
          "sha256": "85204c2fbcb4ea68fd11b9c45da16b691898147a21e3e9d95796ad5b45c41f30",
          "sha1": "5182aefe72fc90b77102a1010d23ec9e5b37909c",
          "md5": "90de4453ea60ac1a1162bc5db5698a4d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.2.1-sources.jar",
          "url": "media3-exoplayer-1.2.1-sources.jar",
          "size": 976274,
          "sha512": "33f61d3385e694a40524627d2df10909158b80c0f4cbeb8eadbfa0da33190c203abde09fe9fd00b7701799f1f8d962ff5c0d4f7a398b21ff0ad1127c8d4ad265",
          "sha256": "46e774740c9e97cdb61493fcf15d9eac8a16ed2dcf38d70a179324b6543cd6c6",
          "sha1": "67c1a38d33fbbcf3649bb7587870a46599bb099c",
          "md5": "f97ce4c75c8e098fc7f5392b7153e410"
        }
      ]
    }
  ]
}
