org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.internal.http.connectionTimeout=120000
org.gradle.internal.http.socketTimeout=120000
org.gradle.internal.http.maxRedirects=5
android.useAndroidX=true
android.nonTransitiveRClass=true
systemProp.org.gradle.internal.repository.disable-on-failure=false
