{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-decoder-1.2.1.aar",
          "url": "media3-decoder-1.2.1.aar",
          "size": 17910,
          "sha512": "ec6ebf31a658511c77b1f0cc73de7670dc47bd20cc76dafb2bd62b8d2ead0381e996244ed29e5c7b2edcbc0f2ad625585587e5ac4f29c28f20b47ee4d9a4eb10",
          "sha256": "8e448a83aff47c7eadb4dbdbfce48086adcdf850bec833450ae69206f83e276d",
          "sha1": "54fbde78e487a5274877e2248db5174fe5734b37",
          "md5": "8e68a7110c99638a5b2889a9f9a38677"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-1.2.1.aar",
          "url": "media3-decoder-1.2.1.aar",
          "size": 17910,
          "sha512": "ec6ebf31a658511c77b1f0cc73de7670dc47bd20cc76dafb2bd62b8d2ead0381e996244ed29e5c7b2edcbc0f2ad625585587e5ac4f29c28f20b47ee4d9a4eb10",
          "sha256": "8e448a83aff47c7eadb4dbdbfce48086adcdf850bec833450ae69206f83e276d",
          "sha1": "54fbde78e487a5274877e2248db5174fe5734b37",
          "md5": "8e68a7110c99638a5b2889a9f9a38677"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-1.2.1-sources.jar",
          "url": "media3-decoder-1.2.1-sources.jar",
          "size": 19168,
          "sha512": "064d14134d4be1501f4603be9fa5da5fc43d8e7c861913730eefe3a0f6df3f3cf8ccabfd727e0c98026f87e096b9633b87bd20dbd6f8a10190e9e157bceea0cb",
          "sha256": "c7d66e04ed8f1bf4cacfec856874f304b2170565f84970103a114fc0743419bd",
          "sha1": "f92e1682946738822e9ec889ef83d712661a954a",
          "md5": "709c624e36dbae8ab609b4c912ca585f"
        }
      ]
    }
  ]
}
