{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-database",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-database-1.2.1.aar",
          "url": "media3-database-1.2.1.aar",
          "size": 7550,
          "sha512": "59448f76541d90153db437f05adb9a6c5cc9133e529c23cefeb8340b9515d55178a32f677b48b1b5bf77981747842424f95f646046c1a4a455e8d981c9cd6ec9",
          "sha256": "254d600819ea03ec4c21e83c3abfefd22c1d1864074e5caaa753188f6c451195",
          "sha1": "8b70c4b1d04c68856b56fc5650ad3a8c33b70dfe",
          "md5": "bf6ace4da31315761cce19817e9e4009"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-database-1.2.1.aar",
          "url": "media3-database-1.2.1.aar",
          "size": 7550,
          "sha512": "59448f76541d90153db437f05adb9a6c5cc9133e529c23cefeb8340b9515d55178a32f677b48b1b5bf77981747842424f95f646046c1a4a455e8d981c9cd6ec9",
          "sha256": "254d600819ea03ec4c21e83c3abfefd22c1d1864074e5caaa753188f6c451195",
          "sha1": "8b70c4b1d04c68856b56fc5650ad3a8c33b70dfe",
          "md5": "bf6ace4da31315761cce19817e9e4009"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-database-1.2.1-sources.jar",
          "url": "media3-database-1.2.1-sources.jar",
          "size": 8744,
          "sha512": "c725938cc2744294d923020a0e7abaa8b9f4590b749b0d85898e21c0feba3e4c4289a0df59ed930e85d5b5493dc495bcb08370ef48bddc31e713eb4d1dfd60bc",
          "sha256": "ca9e9e66db3f341eea6afe5bcd830537c23c877364fbce2e99e48452b470990f",
          "sha1": "892639a5ab076a0acc21b0384d919e9975956009",
          "md5": "a33370ab467e1df451a01f8c2aa37247"
        }
      ]
    }
  ]
}
