{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-multiprocess",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "work-multiprocess-2.7.0.aar",
          "url": "work-multiprocess-2.7.0.aar",
          "size": 98959,
          "sha512": "fef3c262bc412bf08d3f086d69de83b29d204c08a444e73f46df074636de83b845aa91faac01928f01fb2e9cc30c99f80a48931b000a457e9b7f0687d937b7d9",
          "sha256": "b48a9323e21201ed9128102e39453abe2c799fe548a84b40dfb46e3f9542e0ce",
          "sha1": "501ba91fa6a87676c811d1312756488e436498e2",
          "md5": "8a69e6d3d88816bf845292b7bfa4a34c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "work-multiprocess-2.7.0.aar",
          "url": "work-multiprocess-2.7.0.aar",
          "size": 98959,
          "sha512": "fef3c262bc412bf08d3f086d69de83b29d204c08a444e73f46df074636de83b845aa91faac01928f01fb2e9cc30c99f80a48931b000a457e9b7f0687d937b7d9",
          "sha256": "b48a9323e21201ed9128102e39453abe2c799fe548a84b40dfb46e3f9542e0ce",
          "sha1": "501ba91fa6a87676c811d1312756488e436498e2",
          "md5": "8a69e6d3d88816bf845292b7bfa4a34c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-multiprocess-2.7.0-sources.jar",
          "url": "work-multiprocess-2.7.0-sources.jar",
          "size": 46310,
          "sha512": "e87abaa9e160fd1a4520ee943ab835dcd0ee144e0a4dbe223e1a92403e7b0e0a84adad966c5a06c5a8d1a047e78e4bdc442c758903d75e38f74100665785ff44",
          "sha256": "6e6203aa19ea242109458dbd9886f90eecba2a41c8be491d977dcefc407f442b",
          "sha1": "616eb803b9832d770ce8bad1b5fc36143f4117c1",
          "md5": "33212e422fa13e586150917d871c7ef3"
        }
      ]
    }
  ]
}
