{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-datasource-1.2.1.aar",
          "url": "media3-datasource-1.2.1.aar",
          "size": 144210,
          "sha512": "94adfb9857dbae19fdb42232d23bbebed9487bc5ad3c1a098c7cee6f3bec81ff5dafe99a5c387992b2156d675e95a43cd62e63b1edbed537534b26e65d2d4568",
          "sha256": "6da0f6885c853a1ff9e2874f8ecf684d7b8d18d45d8c18bc1b7c495f05a5b4d5",
          "sha1": "38a81cd7c9ef26425a90952bf2d00f6880ed665c",
          "md5": "d0e2321005252c55fa8b173cfc540250"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.2.1.aar",
          "url": "media3-datasource-1.2.1.aar",
          "size": 144210,
          "sha512": "94adfb9857dbae19fdb42232d23bbebed9487bc5ad3c1a098c7cee6f3bec81ff5dafe99a5c387992b2156d675e95a43cd62e63b1edbed537534b26e65d2d4568",
          "sha256": "6da0f6885c853a1ff9e2874f8ecf684d7b8d18d45d8c18bc1b7c495f05a5b4d5",
          "sha1": "38a81cd7c9ef26425a90952bf2d00f6880ed665c",
          "md5": "d0e2321005252c55fa8b173cfc540250"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-1.2.1-sources.jar",
          "url": "media3-datasource-1.2.1-sources.jar",
          "size": 121511,
          "sha512": "f49c0a90f96e2df9f8ae9343917eeca22adeb4b32235fae1182c15a898a6b6128605a6e9884ea102d56ba44f291303a1d1efec940ea34a04a97ca7fe257f3332",
          "sha256": "5d402bcc021f4ced210e4b6c2a6c8a13690ac95804352dee97fc07d081f7c699",
          "sha1": "f853dc1b1c7cd800e056a8acdb208f0dae13c8e4",
          "md5": "6e6df923c222ce2e3042514ea113f43d"
        }
      ]
    }
  ]
}
