version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      compose:
        patterns:
          - "androidx.compose:*"
      camera:
        patterns:
          - "androidx.camera:*"
      ml-kit:
        patterns:
          - "com.google.mlkit:*"
      room:
        patterns:
          - "androidx.room:*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "kotlinx.coroutines:*"