{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-container",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-container-1.2.1.aar",
          "url": "media3-container-1.2.1.aar",
          "size": 23287,
          "sha512": "a21e3777d4d09af29c2b229d976656941f8f0b7cd5a99416f9815ac588bf2011ad07f8e202a4d9580cd8d60a2ac07a19f988f342853284af0e60c2996f26f93c",
          "sha256": "e67d8b50fdb174aa23238f79b3583a485caca9658524b506b5ead6e9c47d1b64",
          "sha1": "ee0108613bbada8d8990fc0065d37e801ec9efee",
          "md5": "639edf6d95590cc7c863b5570ff3243d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-container-1.2.1.aar",
          "url": "media3-container-1.2.1.aar",
          "size": 23287,
          "sha512": "a21e3777d4d09af29c2b229d976656941f8f0b7cd5a99416f9815ac588bf2011ad07f8e202a4d9580cd8d60a2ac07a19f988f342853284af0e60c2996f26f93c",
          "sha256": "e67d8b50fdb174aa23238f79b3583a485caca9658524b506b5ead6e9c47d1b64",
          "sha1": "ee0108613bbada8d8990fc0065d37e801ec9efee",
          "md5": "639edf6d95590cc7c863b5570ff3243d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-container-1.2.1-sources.jar",
          "url": "media3-container-1.2.1-sources.jar",
          "size": 18962,
          "sha512": "ba7978410d1a94399e1b65fae325b5f1c3bd3fa9b44d55b671e8b3c3beb9369e8888d60608218c4931a51959ef2edacb2263c51d6d03d8b55286e2383015ccf4",
          "sha256": "686f67b78306715e2e025b1bab8d5e2624eb4156289fc1846032bb7da5861386",
          "sha1": "62096adf731904b72bc27f77940b7633c6d13dcf",
          "md5": "c4509680dbb9a416116c3a9cad439163"
        }
      ]
    }
  ]
}
