{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-extractor",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-extractor-1.2.1.aar",
          "url": "media3-extractor-1.2.1.aar",
          "size": 734969,
          "sha512": "b48d8502c10b869fdc11d84c066a647da227d3fdc237dcc1de59edb94045109878cd0901429c2d3c8d4c77605d25c08b96f4316e68aa9f9c890b263e723f92dc",
          "sha256": "66955b7f5bcd09d34999723b77ccc727abcdb96fda914dc2e663c282718feeed",
          "sha1": "d362ef57fc630e3d8f8fe08924541a79faf8e6a8",
          "md5": "3c5de95a5378d6af29788acec698bb9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.2.1.aar",
          "url": "media3-extractor-1.2.1.aar",
          "size": 734969,
          "sha512": "b48d8502c10b869fdc11d84c066a647da227d3fdc237dcc1de59edb94045109878cd0901429c2d3c8d4c77605d25c08b96f4316e68aa9f9c890b263e723f92dc",
          "sha256": "66955b7f5bcd09d34999723b77ccc727abcdb96fda914dc2e663c282718feeed",
          "sha1": "d362ef57fc630e3d8f8fe08924541a79faf8e6a8",
          "md5": "3c5de95a5378d6af29788acec698bb9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.2.1-sources.jar",
          "url": "media3-extractor-1.2.1-sources.jar",
          "size": 613572,
          "sha512": "d575ababb5c3b371387fdfa7af7938b64b26f12a7a35526599216739966dbf7de18fa5c6cfd1b4c2a8dd9a0508a8e4b86c7e5464134688d86971e9dd121c8693",
          "sha256": "422990b97086cafe96742ed4f8b5ea8844f9ca85e134fdd7f12b57178dfdc827",
          "sha1": "74ac109908a56aa228730b730dc6888d35dae2d8",
          "md5": "2b190b64bced54c11aef3934e12413c3"
        }
      ]
    }
  ]
}
