{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-ui-1.2.1.aar",
          "url": "media3-ui-1.2.1.aar",
          "size": 432970,
          "sha512": "7be36cfe5dd77068f52c8c2ad6b0db662e27dbdbbbe89f3b4251a93e7c1dd9204097d1f5d0bcf6fd53f30e19547ff434c4bfc44af32d8e7cfbd1ba5275570f57",
          "sha256": "d20c0cfb29b9e412e1941fc26d856318d1af912848e3deb972856950f661cadf",
          "sha1": "8794bbc81c7dd40754e9539fcdda1ba5c999e29b",
          "md5": "4249a8b59d3b87651858764011e132e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.2.1.aar",
          "url": "media3-ui-1.2.1.aar",
          "size": 432970,
          "sha512": "7be36cfe5dd77068f52c8c2ad6b0db662e27dbdbbbe89f3b4251a93e7c1dd9204097d1f5d0bcf6fd53f30e19547ff434c4bfc44af32d8e7cfbd1ba5275570f57",
          "sha256": "d20c0cfb29b9e412e1941fc26d856318d1af912848e3deb972856950f661cadf",
          "sha1": "8794bbc81c7dd40754e9539fcdda1ba5c999e29b",
          "md5": "4249a8b59d3b87651858764011e132e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-1.2.1-sources.jar",
          "url": "media3-ui-1.2.1-sources.jar",
          "size": 111937,
          "sha512": "d5430ac8cc23339e71cc4eac4617c994ec191077aaeea5d5f9d71e8b1072c99495037bcec67e3acf12dec1ea23ffbeea151224636ede728078ef6a5727f89f7f",
          "sha256": "9c37185ae8a9cca31333e11c237a41c9d8f60e2584b00153e8d54c13566c51cb",
          "sha1": "55788ec8e8c7f2d69558554b9457ad133da1be50",
          "md5": "7c430b50cb96f03d8b1beb6d0e0d335b"
        }
      ]
    }
  ]
}
